---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: grpcclient
    labels:
        app: grpcclient
spec:
    replicas: 1
    selector:
        matchLabels:
            app: grpcclient
    template:
        metadata:
            labels:
                app: grpcclient
        spec:
            containers:
                - name: grpcclient
                  image: singhsanket1103/grpc_client
                  env:
                      - name: HOST
                        value: grpc_server
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: grpcserver
    labels:
        app: grpcserver
spec:
    replicas: 1
    selector:
        matchLabels:
            app: grpcserver
    template:
        metadata:
            labels:
                app: grpcserver
        spec:
            containers:
                - name: grpcserver
                  image: singhsanket1103/grpc_server
---
apiVersion: v1
kind: Service
metadata:
    name: grpcserver
spec:
    selector:
        app: grpcserver
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: grpcclient
spec:
    type: LoadBalancer
    selector:
        app: grpcclient
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000